### PR TITLE
update protobuf.version to 3.19.6

### PR DESCRIPTION
**Pull request by weiZhenkun**
Signed-off-by: weizhenkun [247910571@qq.com](mailto:247910571@qq.com)

### CODE REVIEW

**Comment by yhmo** [comment]
@weiZhenkun 
The DCO check is not passed. 
Refer this doc to know how to set DCO: https://www.secondstate.io/articles/dco/

**Comment by weiZhenkun** [comment]
Signed-off-by: wei zhenkun <247910571@qq.com>

**Pull request closed without merging**
