### PR TITLE
Add control logic param definition

### PR DESCRIPTION
**Pull request by Javajava1**
add some param definition for control path

### CODE REVIEW

**Comment by Javajava1** [comment]
resolve the conflict,add comments to api interface,use "git commit -sm "...."" command commit the code.

**Review by xiaofan-luan — APPROVED** [review]
Looks good to me

**Comment by xiaofan-luan** [comment]
Great job Javajava1, thanks for the contribution

**Comment by Javajava1** [comment]
> Great job Javajava1, thanks for the contribution

It is my pleasure to contribute my pygmy effort.

**Pull request merged**
