### PR TITLE
MetricType was not initialized in SearchIterator#executeNextSearch (#881), and cast errors occured in SearchIterator#checkRmRangeSearchParameters (#887)

### PR DESCRIPTION
**Pull request by PiercarloSlavazza**
MetricType was not initialized in SearchIterator#executeNextSearch (#881)

### CODE REVIEW

**Comment by PiercarloSlavazza** [comment]
This is a fix for #881 - sorry, this is my 1st PR and I have not been able to link to it

**Comment by yhmo** [comment]
@PiercarloSlavazza 
The DCO is not passed. It requires a mail address in the commit description.
Could you modify your commit in this way:
1. git commit --amend
2. edit the commit description, add your github account and mail address like this:
```
    MetricType was not initialized in SearchIterator#executeNextSearch (https://github.com/milvus-io/milvus-sdk-java/issues/881)
    
    Signed-off-by: PiercarloSlavazza <your email address>
```

**Comment by PiercarloSlavazza** [comment]
@yhmo sign off added - I think we can merge now

**Comment by PiercarloSlavazza** [comment]
Added a fix for #887

**Comment by PiercarloSlavazza** [comment]
Removed fix for #887 because a patched has been already landed on master via commit ae9ba7b

**Pull request merged**
