### PR TITLE
Support gRPC timeout, target string and load-balancing policy

### PR DESCRIPTION
**Pull request by thirstycrow**
It's essentially what's already done to 0.8.x with #128, #129 and #130, with a modification to the `ContainerMilvusClientTest.loadBalancing` to make it work with containers of the same version.

### CODE REVIEW

**Comment by sahuang** [comment]
Hi, thanks for the pull request. 

There was a change in Milvus v0.11.0 [in this PR](https://github.com/milvus-io/milvus/pull/3724/) that changed all usages of `segment_row_count` to `segment_row_limit`. Can you please change accordingly? I forgot to change it when I pushed the sdk 0.9.0 branch.

On the other hand, is this pull request separate from #134 ?

Thanks again for the contribution.

**Comment by thirstycrow** [comment]
> There was a change in Milvus v0.11.0 in this PR that changed all usages of segment_row_count to segment_row_limit. Can you please change accordingly? I forgot to change it when I pushed the sdk 0.9.0 branch.
I added a commit to change `segment_row_count` to `segment_row_limit` in the beginning

> Edit: It seems that #134 includes all commits from this pull request.
Yes, #134 is base on #133.

**Comment by sahuang** [comment]
> Yes, #134 is base on #133.

Does it mean this PR can be closed and I only need to review/merge #134 ?

**Comment by sahuang** [comment]
> Yes, #134 is base on #133.

If that's the case, shall I close this PR and review #134 only?

**Comment by thirstycrow** [comment]
> If that's the case, shall I close this PR and review #134 only?

I think it would be better to review and merge this one first. #134 is independent, I rebased it to this one so you do not have to review the same code twice once the one get merged.

**Pull request merged**
