### PR TITLE
fix concat expr error

### PR DESCRIPTION
**Pull request by Ice-YcY**
concat expr error 
image

### CODE REVIEW

**Comment by Ice-YcY** [comment]
@yelusion2 @yhmo

**Comment by yhmo** [comment]
@Ice-YcY 
The DCO check is not passed.
You can use "git commit --amend" to edit the commit, and include `Signed-off-by: Author Name <authoremail@example.com> ` in the description.

**Comment by Ice-YcY** [comment]
add Signed-off-by &  created another PR for 2.4 & 2.3

**Comment by xiaofan-luan** [comment]
@Ice-YcY 
please update your tco

**Pull request merged**
