### PR TITLE
Use Testcontainers Milvus module

### PR DESCRIPTION
**Pull request by eddumelendez**
[Testcontainers](https://testcontainers.com/) 1.19.6 provides a milvus module. It uses an embedded
etcd and local storage.

### CODE REVIEW

**Comment by eddumelendez** [comment]
[MilvusMultiClientDockerTest](https://github.com/milvus-io/milvus-sdk-java/blob/master/src/test/java/io/milvus/client/MilvusMultiClientDockerTest.java) can also be moved because Testcontainers also provide a minio module and etcd can be used using GenericContainer.

**Comment by yhmo** [comment]
@eddumelendez eddumelendez
The CI is not passed. Could you double-check the cases in MilvusClientDockerTest and MilvusMultiClientDockerTest can pass in your local?

**Comment by eddumelendez** [comment]
@yhmo PR updated. I have excluded the dependencies to use the ones provided by milvus itself. Tests are running fine locally.

**Comment by yhmo** [comment]
With the testcontainers integrated, I ran the test case for the first time and encountered a timeout error that said the image testcontainers/ryuk:0.6.0 could not be pulled.
I manually download the image by `docker pull testcontainers/ryuk:0.6.0` and the test case is succeed to pass.

Just note here for the people who may encounter this error in the future.

**Pull request merged**
