### PR TITLE
fix: unused `buf2` in `v2/Float16VectorExample.java` example

### PR DESCRIPTION
**Pull request by jiangyinzuo**

### CODE REVIEW

**Comment by yhmo** [comment]
@jiangyinzuo 
Thanks for fix. Could you cherry-pick this fix to the 2.4 branch?

**Comment by jiangyinzuo** [comment]
> @jiangyinzuo Thanks for fix. Could you cherry-pick this fix to the 2.4 branch?

See #1165

**Comment by jiangyinzuo** [comment]
> @jiangyinzuo Thanks for fix. Could you cherry-pick this fix to the 2.4 branch?

See #1166

**Pull request merged**
