### PR TITLE
Fix shutdown of channel

### PR DESCRIPTION
**Pull request by dddddai**
Remove redundant loop and simplify the code

### CODE REVIEW

**Comment by sahuang** [comment]
Hi, thanks for the pull request. I think the change you proposed is similar to what I did before v0.8.5. @thirstycrow did a few changes to the timeout and shutdown of Milvus server and used this method. The reason can be seen from [this commit message](https://github.com/milvus-io/milvus-sdk-java/pull/128/commits/0c36a9a3634f144ad2e5123fdde59d8ef5e464ff).

**Comment by dddddai** [comment]
> Hi, thanks for the pull request. I think the change you proposed is similar to what I did before v0.8.5. @thirstycrow did a few changes to the timeout and shutdown of Milvus server and used this method. The reason can be seen from [this commit message](https://github.com/milvus-io/milvus-sdk-java/pull/128/commits/0c36a9a3634f144ad2e5123fdde59d8ef5e464ff).

Thanks for your review. I did not changed the logic but just simplify the code.

And the while loop doesn't make sense to me.
1.`now` never has never changed in the loop.
2.`awaitTermination` waits for a timeout, there is no need to use a while loop.

https://github.com/milvus-io/milvus-sdk-java/blob/master/src/main/java/io/milvus/client/MilvusGrpcClient.java#L111-L132

**Comment by sahuang** [comment]
Thanks for the explanation, I think your point is valid and should be correct.

@thirstycrow do you mind explaining your rationale? I also feel that the while loop/now is not necessary.

**Comment by thirstycrow** [comment]
My intention was to put off any interruption until the shutdown complete normally or timed out, because I am not sure whether it is possible for the method to receive an unintended interruption. The current timestamp (`now`) should have been updated at the end of the while block.

**Comment by sahuang** [comment]
The simplified version seems alright to me, I don't feel it's really necessary to consider unintended interruption when it comes to shutting down the channel and server.

**Pull request merged**
