### PR TITLE
pretty code style

### PR DESCRIPTION
**Pull request by ChunelFeng**
Add some file header when missed, pretty code style, correct some param spelling, without any code changed.

### CODE REVIEW

**Comment by xiaofan-luan** [comment]
Welcome chunnel!

**Comment by ChunelFeng** [comment]
> Welcome chunnel!

spelling mistake

**Comment by xiaofan-luan** [comment]
> > Welcome chunnel!
> 
> Spelling mistake, this is Chunel

lol

**Review by xiaofan-luan — APPROVED** [review]
LGTM, Thnaks

**Pull request closed without merging**
